  
language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "krishna192168"
    token:
      secure: f2810fc934c7f897bd9d35c6143ae234b54cdee3 # sonor encrypted token

cache:
  directories:
    - '$HOME/.gradle/caches/'
    - '$HOME/.gradle/wrapper/'

script:
  # here builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ./gradlew sonarqube
  
notifications:
  email:
    - krishna192168@gmail.com
    - yaswanthlakshmi986@gmail.com
